/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var View = Laya.View;
var Dialog = Laya.Dialog;
var Scene = Laya.Scene;
var REG = Laya.ClassUtils.regClass;
class NativeIconUI extends View {
    constructor() {
        super();
    }
    createChildren() {
        super.createChildren();
        this.createView(NativeIconUI.uiView);
    }

}
NativeIconUI.uiView = {
    "type": "View",
    "props": {
        "width": 90,
        "height": 120
    },
    "compId": 2,
    "child": [{
        "type": "Image",
        "props": {
            "y": 0,
            "x": 0,
            "width": 90,
            "var": "bj",
            "skin": "ADRes/native_6.png",
            "height": 120
        },
        "compId": 3
    }, {
        "type": "Image",
        "props": {
            "y": 15.5,
            "x": 9,
            "width": 70,
            "var": "icon",
            "height": 70
        },
        "compId": 5
    }, {
        "type": "Label",
        "props": {
            "y": 81,
            "x": 11,
            "width": 68,
            "var": "title",
            "valign": "middle",
            "text": "wwwwwwwwwwwwwww",
            "overflow": "scroll",
            "height": 27,
            "fontSize": 20,
            "color": "#080707",
            "align": "center"
        },
        "compId": 7
    }, {
        "type": "Image",
        "props": {
            "y": 108,
            "x": 59,
            "width": 31,
            "var": "ad",
            "skin": "ADRes/native_1.png",
            "height": 12
        },
        "compId": 9
    }],
    "loadList": ["ADRes/native_6.png", "ADRes/native_1.png"],
    "loadList3D": []
};
REG("ui.UI.AD.NativeIconUI", NativeIconUI);
class NativeInsertUI extends View {
    constructor() {
        super();
    }
    createChildren() {
        super.createChildren();
        this.createView(NativeInsertUI.uiView);
    }

}
NativeInsertUI.uiView = {
    "type": "View",
    "props": {
        "width": 720,
        "height": 1280
    },
    "compId": 2,
    "child": [{
        "type": "Image",
        "props": {
            "var": "heidi",
            "top": -300,
            "skin": "ADRes/heidi90.png",
            "sizeGrid": "5,5,5,5",
            "right": -300,
            "left": -300,
            "bottom": -300,
            "alpha": 0.8
        },
        "compId": 13
    }, {
        "type": "Box",
        "props": {
            "width": 640,
            "height": 400,
            "centerY": -56,
            "centerX": 0
        },
        "compId": 4,
        "child": [{
            "type": "Image",
            "props": {
                "var": "bj",
                "top": 0,
                "skin": "ADRes/native_2.png",
                "right": 0,
                "left": 0,
                "bottom": 0
            },
            "compId": 3
        }, {
            "type": "Image",
            "props": {
                "y": 111,
                "x": 260,
                "width": 120,
                "var": "icon",
                "height": 120
            },
            "compId": 6
        }, {
            "type": "Image",
            "props": {
                "y": 25,
                "x": 30,
                "width": 35,
                "var": "close",
                "stateNum": 1,
                "skin": "ADRes/native_3.png",
                "height": 35,
                "anchorY": 0.5,
                "anchorX": 0.5
            },
            "compId": 10
        }, {
            "type": "Image",
            "props": {
                "y": 308,
                "x": 0,
                "width": 640,
                "skin": "ADRes/native_6.png",
                "height": 92
            },
            "compId": 11
        }, {
            "type": "Image",
            "props": {
                "y": 326,
                "x": 517.5,
                "skin": "ADRes/native_5.png"
            },
            "compId": 12
        }, {
            "type": "Label",
            "props": {
                "y": 353,
                "x": 27,
                "width": 529,
                "var": "des",
                "valign": "middle",
                "text": "label",
                "height": 43,
                "fontSize": 20,
                "color": "#000000"
            },
            "compId": 9
        }, {
            "type": "Label",
            "props": {
                "y": 311,
                "x": 27,
                "width": 516,
                "var": "title",
                "valign": "middle",
                "text": "wwwwwwwwwwwwwww",
                "height": 35,
                "fontSize": 20,
                "color": "#696969",
                "align": "left"
            },
            "compId": 8
        }, {
            "type": "Image",
            "props": {
                "y": 369,
                "x": 557,
                "var": "ad",
                "skin": "ADRes/native_1.png",
                "right": 0,
                "bottom": 0
            },
            "compId": 5
        }, {
            "type": "Image",
            "props": {
                "y": 431,
                "var": "click",
                "skin": "ADRes/button_common_01.png",
                "label": "label",
                "centerX": 0
            },
            "compId": 14,
            "child": [{
                "type": "Image",
                "props": {
                    "skin": "ADRes/Image_add_13.png",
                    "centerY": 0,
                    "centerX": 0
                },
                "compId": 15
            }]
        }]
    }],
    "loadList": ["ADRes/heidi90.png", "ADRes/native_2.png", "ADRes/native_3.png", "ADRes/native_6.png", "ADRes/native_5.png", "ADRes/native_1.png", "ADRes/button_common_01.png", "ADRes/Image_add_13.png"],
    "loadList3D": []
};
REG("ui.UI.AD.NativeInsertUI", NativeInsertUI);
class GameTipUI extends View {
    constructor() {
        super();
    }
    createChildren() {
        super.createChildren();
        this.createView(GameTipUI.uiView);
    }

}
GameTipUI.uiView = {
    "type": "View",
    "props": {
        "width": 720,
        "height": 1280
    },
    "compId": 2,
    "child": [{
        "type": "Label",
        "props": {
            "y": 0,
            "x": 0,
            "width": 400,
            "var": "value",
            "valign": "middle",
            "text": "金币不足",
            "strokeColor": "#080808",
            "stroke": 1,
            "height": 67,
            "fontSize": 30,
            "color": "#ffffff",
            "borderColor": "#ffffff",
            "bold": true,
            "bgColor": "#232323",
            "anchorY": 0.5,
            "anchorX": 0.5,
            "align": "center"
        },
        "compId": 4
    }],
    "animations": [{
        "nodes": [{
            "target": 4,
            "keyframes": {
                "y": [{
                    "value": 0,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 4,
                    "key": "y",
                    "index": 0
                }, {
                    "value": -40,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 4,
                    "key": "y",
                    "index": 20
                }],
                "x": [{
                    "value": 0,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 4,
                    "key": "x",
                    "index": 0
                }],
                "alpha": [{
                    "value": 1,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 4,
                    "key": "alpha",
                    "index": 0
                }, {
                    "value": 1,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 4,
                    "key": "alpha",
                    "index": 20
                }, {
                    "value": 1,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 4,
                    "key": "alpha",
                    "index": 40
                }, {
                    "value": 0,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 4,
                    "key": "alpha",
                    "index": 60
                }]
            }
        }],
        "name": "ani1",
        "id": 1,
        "frameRate": 24,
        "action": 1
    }],
    "loadList": [],
    "loadList3D": []
};
REG("ui.Prefab.GameTipUI", GameTipUI);
class HTMoreGameUI extends View {
    constructor() {
        super();
    }
    createChildren() {
        super.createChildren();
        this.createView(HTMoreGameUI.uiView);
    }

}
HTMoreGameUI.uiView = {
    "type": "View",
    "props": {
        "width": 120,
        "isShowEffect": false,
        "isModal": true,
        "height": 120
    },
    "compId": 2,
    "child": [{
        "type": "Image",
        "props": {
            "y": 59,
            "x": 60,
            "skin": "HTRes/moreGame.png",
            "anchorY": 0.5,
            "anchorX": 0.5
        },
        "compId": 72,
        "child": [{
            "type": "Image",
            "props": {
                "y": 1,
                "x": 95,
                "var": "redImg",
                "skin": "HTRes/red.png",
                "right": 0
            },
            "compId": 73
        }]
    }],
    "animations": [{
        "nodes": [{
            "target": 72,
            "keyframes": {
                "rotation": [{
                    "value": 0,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 72,
                    "key": "rotation",
                    "index": 0
                }, {
                    "value": -35,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 72,
                    "key": "rotation",
                    "index": 4
                }, {
                    "value": 30,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 72,
                    "key": "rotation",
                    "index": 8
                }, {
                    "value": -25,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 72,
                    "key": "rotation",
                    "index": 12
                }, {
                    "value": 15,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 72,
                    "key": "rotation",
                    "index": 16
                }, {
                    "value": 0,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 72,
                    "key": "rotation",
                    "index": 20
                }, {
                    "value": 0,
                    "tweenMethod": "linearNone",
                    "tween": true,
                    "target": 72,
                    "label": null,
                    "key": "rotation",
                    "index": 60
                }]
            }
        }],
        "name": "ani1",
        "id": 1,
        "frameRate": 24,
        "action": 2
    }],
    "loadList": ["HTRes/moreGame.png", "HTRes/red.png"],
    "loadList3D": []
};
REG("ui.HuTui.HTMoreGameUI", HTMoreGameUI);

class YinSiUI extends View {
    constructor() {
        super();
    }
    createChildren() {
        super.createChildren();
        this.createView(YinSiUI.uiView);
    }

}
YinSiUI.uiView = {
    "type": "View",
    "props": {
        "width": 720,
        "height": 1280
    },
    "compId": 2,
    "child": [{
        "type": "Image",
        "props": {
            "y": -517,
            "x": -140,
            "width": 1000,
            "skin": "ADRes/heidi90.png",
            "sizeGrid": "5,8,5,7",
            "height": 3000,
            "alpha": 0.5
        },
        "compId": 6
    }, {
        "type": "Image",
        "props": {
            "var": "panel1",
            "skin": "ADRes/white.png",
            "sizeGrid": "18,13,38,10",
            "right": 30,
            "left": 30,
            "height": 1000,
            "centerY": 0
        },
        "compId": 3,
        "child": [{
            "type": "Image",
            "props": {
                "top": 110,
                "text": "text",
                "skin": "ADRes/huidi.png",
                "sizeGrid": "20,13,19,20",
                "right": 20,
                "left": 20,
                "bottom": 110
            },
            "compId": 41
        }, {
            "type": "Label",
            "props": {
                "y": 33,
                "var": "label2",
                "valign": "middle",
                "text": "隐私协议",
                "right": 0,
                "left": -1,
                "fontSize": 40,
                "bold": true,
                "align": "center"
            },
            "compId": 39
        }, {
            "type": "Text",
            "props": {
                "y": 122,
                "x": 33,
                "wordWrap": true,
                "width": 589,
                "var": "text2",
                "text": "生效日期: 2021年10月1日nn提示条款nn本软件尊重并保护所有使用服务用户的个人隐私权。为了给您提供更准nn确、更有个性化的服务，本软件会按照本隐私权政策的规定使用和披露nn您的个人信息。但本软件将以高度的勤勉、审慎义务对待这些信息。除nn本隐私权政策另有规定外，在未征得您事先许可的情况下，本软件不会nn将这些信息对外披露或向第三方提供。本软件会不时更新本隐私权政策nn。您在同意本软件服务使用协议之时，即视为您已经同意本隐私权政策nn全部内容。本隐私权政策属于本软件服务使用协议不可分割的一部分。nn1.适用范围nna)在您使用本软件网络服务，本软件自动接收并记录的您的手机上的nn信息，包括但不限于您的健康数据、使用的语言、访问日期和时间、nn软硬件特征信息及您需求的网页记录等数据;nn2.信息的使用nna)在获得您的数据之后，本软件会将其上传至服务器，以生成您的排nn行榜数据，以便您能够更好地使用服务。nn3.信息披露nna)本软件不会将您的信息披露给不受信任的第三方。nnb)根据法律的有关规定，或者行政或司法机构的要求，向第三方或者nn行政、司法机构披露;nnc)如您出现违反中国有关法律、法规或者相关规则的情况，需要向第nn三方披露;nn4.信息存储和交换nn本软件收集的有关您的信息和资料将保存在本软件及(或)其关联公nn司的服务器上，这些信息和资料可能传送至您所在国家、地区或本软nn件收集信息和资料所在地的境外并在境外被访问、存储和展示。nn5.信息安全nn在使用本软件网络服务进行网上交易时，您不可避免的要向交易对nn方或潜在的交易对方披露自己的个人信息，如联络方式或者邮政地址nn请您妥善保护自己的个人信息，仅在必要的情形下向他人提供。如nn您发现自己的个人信息泄密，请您立即联络本软件客服，以便本软件nn采取相应措施。nn",
                "overflow": "scroll",
                "leading": 5,
                "height": 767,
                "fontSize": 20,
                "bold": true,
                "runtime": "Laya.Text"
            },
            "compId": 40
        }, {
            "type": "Button",
            "props": {
                "var": "okbtn",
                "stateNum": 1,
                "skin": "ADRes/tongyi.png",
                "labelStrokeColor": "#ffffff",
                "labelSize": 30,
                "labelColors": "#ffffff",
                "labelBold": true,
                "centerX": 150,
                "bottom": 10
            },
            "compId": 7
        }, {
            "type": "Button",
            "props": {
                "var": "closebtn",
                "stateNum": 1,
                "skin": "ADRes/jujue.png",
                "labelBold": false,
                "centerX": -150,
                "bottom": 10
            },
            "compId": 8
        }, {
            "type": "Button",
            "props": {
                "x": 115,
                "var": "okbtn1",
                "stateNum": 1,
                "skin": "ADRes/guanbi.png",
                "labelStrokeColor": "#ffffff",
                "labelSize": 30,
                "labelColors": "#ffffff",
                "labelBold": true,
                "centerX": 0,
                "bottom": 10
            },
            "compId": 15
        }]
    }],
    "loadList": ["ADRes/heidi90.png", "ADRes/white.png", "ADRes/huidi.png", "ADRes/tongyi.png", "ADRes/jujue.png", "ADRes/guanbi.png"],
    "loadList3D": []
};
REG("ui.YinSiUI", YinSiUI);

class YinSiHUI extends View {
    constructor() {
        super();
    }
    createChildren() {
        super.createChildren();
        this.createView(YinSiHUI.uiView);
    }

}
YinSiHUI.uiView = {
    "type": "View",
    "props": {
        "width": 1280,
        "height": 720
    },
    "compId": 2,
    "child": [{
        "type": "Image",
        "props": {
            "y": -1140,
            "x": -516,
            "width": 2262,
            "skin": "ADRes/heidi90.png",
            "sizeGrid": "5,8,5,7",
            "height": 3000,
            "alpha": 0.5
        },
        "compId": 6
    }, {
        "type": "Image",
        "props": {
            "width": 700,
            "var": "panel1",
            "skin": "ADRes/white.png",
            "sizeGrid": "18,13,38,10",
            "height": 600,
            "centerY": 0,
            "centerX": -70,
            "scaleX": 0.6,
            "scaleY": 0.6
        },
        "compId": 3,
        "child": [{
            "type": "Image",
            "props": {
                "top": 110,
                "text": "text",
                "skin": "ADRes/huidi.png",
                "sizeGrid": "20,13,19,20",
                "right": 20,
                "left": 20,
                "bottom": 110
            },
            "compId": 41
        }, {
            "type": "Label",
            "props": {
                "y": 33,
                "var": "label2",
                "valign": "middle",
                "text": "隐私协议",
                "right": 0,
                "left": -1,
                "fontSize": 40,
                "bold": true,
                "align": "center"
            },
            "compId": 39
        }, {
            "type": "Text",
            "props": {
                "y": 122,
                "x": 33,
                "wordWrap": true,
                "width": 636,
                "var": "text2",
                "text": "生效日期: 2021年10月1日nn提示条款nn本软件尊重并保护所有使用服务用户的个人隐私权。为了给您提供更准nn确、更有个性化的服务，本软件会按照本隐私权政策的规定使用和披露nn您的个人信息。但本软件将以高度的勤勉、审慎义务对待这些信息。除nn本隐私权政策另有规定外，在未征得您事先许可的情况下，本软件不会nn将这些信息对外披露或向第三方提供。本软件会不时更新本隐私权政策nn。您在同意本软件服务使用协议之时，即视为您已经同意本隐私权政策nn全部内容。本隐私权政策属于本软件服务使用协议不可分割的一部分。nn1.适用范围nna)在您使用本软件网络服务，本软件自动接收并记录的您的手机上的nn信息，包括但不限于您的健康数据、使用的语言、访问日期和时间、nn软硬件特征信息及您需求的网页记录等数据;nn2.信息的使用nna)在获得您的数据之后，本软件会将其上传至服务器，以生成您的排nn行榜数据，以便您能够更好地使用服务。nn3.信息披露nna)本软件不会将您的信息披露给不受信任的第三方。nnb)根据法律的有关规定，或者行政或司法机构的要求，向第三方或者nn行政、司法机构披露;nnc)如您出现违反中国有关法律、法规或者相关规则的情况，需要向第nn三方披露;nn4.信息存储和交换nn本软件收集的有关您的信息和资料将保存在本软件及(或)其关联公nn司的服务器上，这些信息和资料可能传送至您所在国家、地区或本软nn件收集信息和资料所在地的境外并在境外被访问、存储和展示。nn5.信息安全nn在使用本软件网络服务进行网上交易时，您不可避免的要向交易对nn方或潜在的交易对方披露自己的个人信息，如联络方式或者邮政地址nn请您妥善保护自己的个人信息，仅在必要的情形下向他人提供。如nn您发现自己的个人信息泄密，请您立即联络本软件客服，以便本软件nn采取相应措施。nn",
                "overflow": "scroll",
                "leading": 5,
                "height": 359,
                "fontSize": 20,
                "bold": true,
                "runtime": "Laya.Text"
            },
            "compId": 40
        }, {
            "type": "Button",
            "props": {
                "var": "okbtn",
                "stateNum": 1,
                "skin": "ADRes/tongyi.png",
                "scaleY": 0.8,
                "scaleX": 0.8,
                "labelStrokeColor": "#ffffff",
                "labelSize": 30,
                "labelColors": "#ffffff",
                "labelBold": true,
                "centerX": 150,
                "bottom": 20
            },
            "compId": 7
        }, {
            "type": "Button",
            "props": {
                "var": "closebtn",
                "stateNum": 1,
                "skin": "ADRes/jujue.png",
                "scaleY": 0.8,
                "scaleX": 0.8,
                "labelBold": false,
                "centerX": -150,
                "bottom": 20
            },
            "compId": 8
        }, {
            "type": "Button",
            "props": {
                "x": 115,
                "var": "okbtn1",
                "stateNum": 1,
                "skin": "ADRes/guanbi.png",
                "scaleY": 0.8,
                "scaleX": 0.8,
                "labelStrokeColor": "#ffffff",
                "labelSize": 30,
                "labelColors": "#ffffff",
                "labelBold": true,
                "centerX": 0,
                "bottom": 20
            },
            "compId": 15
        }]
    }],
    "loadList": ["ADRes/heidi90.png", "ADRes/white.png", "ADRes/huidi.png", "ADRes/tongyi.png", "ADRes/jujue.png", "ADRes/guanbi.png"],
    "loadList3D": []
};
REG("ui.YinSiHUI", YinSiHUI);

class YinSiBtnUI extends View {
    constructor() {
        super();
    }
    createChildren() {
        super.createChildren();
        this.createView(YinSiBtnUI.uiView);
    }

}
YinSiBtnUI.uiView = {
    "type": "View",
    "props": {
        "width": 100,
        "isShowEffect": false,
        "isModal": true,
        "height": 100
    },
    "compId": 2,
    "child": [{
        "type": "Image",
        "props": {
            "var": "btn",
            "top": 0,
            "skin": "ADRes/sz.png",
            "right": 0,
            "left": 0,
            "bottom": 0,
            "anchorY": 0.5,
            "anchorX": 0.5
        },
        "compId": 72
    }],
    "loadList": ["ADRes/sz.png"],
    "loadList3D": []
};
REG("ui.YinSiBtnUI", YinSiBtnUI);
class ZhenDongBtnUI extends View {
    constructor() {
        super();
    }
    createChildren() {
        super.createChildren();
        this.createView(ZhenDongBtnUI.uiView);
    }

}
ZhenDongBtnUI.uiView = {
    "type": "View",
    "props": {
        "width": 100,
        "isShowEffect": false,
        "isModal": true,
        "height": 100
    },
    "compId": 2,
    "child": [{
        "type": "Image",
        "props": {
            "var": "btn",
            "top": 0,
            "skin": "ADRes/zddk.png",
            "right": 0,
            "left": 0,
            "bottom": 0,
            "anchorY": 0.5,
            "anchorX": 0.5
        },
        "compId": 72
    }],
    "loadList": ["ADRes/zddk.png"],
    "loadList3D": []
};
REG("ui.ZhenDongBtnUI", ZhenDongBtnUI);
class ShiLingTipUI extends View {
    constructor() {
        super();
    }
    createChildren() {
        super.createChildren();
        this.createView(ShiLingTipUI.uiView);
    }

}
ShiLingTipUI.uiView = {
    "type": "View",
    "props": {
        "width": 720,
        "height": 1280
    },
    "compId": 2,
    "child": [{
        "type": "Image",
        "props": {
            "y": -517,
            "x": -140,
            "width": 1000,
            "skin": "ADRes/heidi90.png",
            "sizeGrid": "5,8,5,7",
            "height": 3000,
            "alpha": 0.5
        },
        "compId": 6
    }, {
        "type": "Image",
        "props": {
            "width": 600,
            "var": "panel1",
            "skin": "ADRes/white.png",
            "height": 565,
            "centerY": 0,
            "centerX": 0
        },
        "compId": 3,
        "child": [{
            "type": "Label",
            "props": {
                "y": 17,
                "x": 147.0703125,
                "valign": "middle",
                "text": "适龄提示说明",
                "fontSize": 50,
                "bold": true,
                "align": "center"
            },
            "compId": 42
        }, {
            "type": "Label",
            "props": {
                "y": 86,
                "x": 32,
                "wordWrap": true,
                "width": 536,
                "var": "yonghubtn",
                "valign": "middle",
                "text": "1）本游戏是一款简单的休闲益智类游戏,适用于年满8周岁及以上的用户,建议未成年人在家长监护下使用游戏产品。2)本游戏基于架空的故事背景和幻想世界观,剧情简单且积极向上,没有基于真实历史和现实事件的改编内容。游戏玩法基于肢体操作，鼓励玩家通过行动达成目标。游戏中没有基于文字和语音的陌生人社交系统。3）本游戏以益智闯关为主题,有助于锻炼玩家的大脑反应速度和手眼协调能力，能够带给玩家积极愉悦的情绪体验,增强玩家的自信心。",
                "leading": 15,
                "height": 349,
                "fontSize": 22,
                "color": "#52a1e3",
                "bold": true,
                "align": "left"
            },
            "compId": 11
        }, {
            "type": "Button",
            "props": {
                "y": 464,
                "var": "okbtn",
                "stateNum": 1,
                "skin": "ADRes/button.png",
                "labelStrokeColor": "#ffffff",
                "labelSize": 30,
                "labelColors": "#ffffff",
                "labelBold": true,
                "label": "确 定",
                "centerX": 0
            },
            "compId": 7
        }]
    }],
    "loadList": ["ADRes/heidi90.png", "ADRes/white.png", "ADRes/button.png"],
    "loadList3D": []
};
REG("ui.ShiLingTipUI", ShiLingTipUI);

window.SdkUtil = {
    banben: window.GameParameter["versionCode"].val,
    nativeADTag: {
        "1": "推送界面",
        "2": "胜利界面",
        "3": "宝箱界面",
        "4": "未知4",
        "5": "未知5"
    },
    nativeAD: {
        "1": window.GameParameter["nativeAD1"].val,
        "2": window.GameParameter["nativeAD2"].val,
        "3": window.GameParameter["nativeAD3"].val,
        "4": window.GameParameter["nativeAD3"].val,
        "5": window.GameParameter["nativeAD3"].val
    },
    videoId: window.GameParameter["videoId"].val,
    yuanshengmoban: window.GameParameter["yuanshengmoban"] ? window.GameParameter["yuanshengmoban"].val : "",
    bannerId: window.GameParameter["bannerId"].val,
    bannerHTID: window.GameParameter["bannerHTID"].val,
    jiugongHTId: window.GameParameter["jiugongHTId"].val,
    HTLunBoBannerId: window.GameParameter["HTLunBoBannerId"].val,
    subpkgnum: parseInt(window.GameParameter["subpackages"].val),
    screenOrientation: window.GameParameter["screenOrientation"].val,
    ADInit: function (showZhenDong) {
        SdkUtil.showZhenDong = showZhenDong;
        SdkUtil.TDInit();
        window["oppoChannel"] = true;
        // qg.initAdService({
        //     appId: window.GameParameter["appid"].val,
        //     isDebug: true,
        //     success: function (res) {
        //         console.log("initAdService success");
        //     },
        //     fail: function (res) {
        //         console.log("initAdService fail:" + res.code + res.msg);
        //     },
        //     complete: function (res) {
        //         console.log("initAdService complete");
        //     }
        // })
        SdkUtil.jishu01 = 0;
        SdkUtil.bnanerShowTime = new Date().getTime();
        SdkUtil.addIconShowTime = new Date().getTime() + 120000;
        SdkUtil.qiehuanUINum = 0;

        if (window.navigator == null) {
            window.navigator = {};
        }
        SdkUtil.iszhendong = true;
        window.navigator.vibrate = function () {
            // if (qg.vibrateShort && SdkUtil.iszhendong) {
            //     qg.vibrateShort({
            //         success: function (res) { },
            //         fail: function (res) { },
            //         complete: function (res) { }
            //     })
            // }
        }
        if (Laya.LocalStorage.getItem("fristRun")) {
            SdkUtil.fristRun = Laya.LocalStorage.getItem("fristRun");
        }
        Laya.LocalStorage.setItem("fristRun", 1);

        SdkUtil.TDGuanQia(1, "-1");
        GameConfig.GetServerConfig(window.GameParameter["biaoqian"].val + "" + SdkUtil.banben);

        SdkUtil.qidongTime = new Date().getTime();

        return SdkUtil.banben;
    },
    ChangeGamePanel(url) {
        // if(window.morencanshu&&window.morencanshu.ChangeGamePanel)
        // {
        //     return window.morencanshu.ChangeGamePanel(url)
        // }
        // if(url)
        // {
        //     if(SdkUtil.RandomInt(0,100)<SdkUtil.GetConfig("jm"))
        //     {
        //         if(url.indexOf("Push.scene")!=-1)
        //         {
        //             url = url.replace("Push","Push_oppo1") ;
        //         }
        //         if(url.indexOf("Box.scene")!=-1)
        //         {
        //             url = url.replace("Box","Box_oppo1") ;
        //         }
        //         if(url.indexOf("Win.scene")!=-1)
        //         {
        //             url = url.replace("Win","Win_oppo1") ;
        //         }
        //     }
        //     else
        //     {
        //         if(url.indexOf("Push.scene")!=-1)
        //         {
        //             url = url.replace("Push","Push_oppo") ;
        //         }
        //         if(url.indexOf("Box.scene")!=-1)
        //         {
        //             url = url.replace("Box","Box_oppo") ;
        //         }
        //         if(url.indexOf("Win.scene")!=-1)
        //         {
        //             url = url.replace("Win","Win_oppo") ;
        //         }
        //     }
        //     if(url.indexOf("Fail.scene")!=-1)
        //     {
        //         url = url.replace("Fail","Fail_ht") ;
        //         SdkUtil.ShowHuTuiBanner();
        //         SdkUtil.PushNum = 0 ;
        //         SdkUtil.BoxNum = 0 ;
        //         SdkUtil.WinNum = 0 ;
        //     }
        // }
        return url;
    },
    UpdateGamePanel(panel) {
        if (panel && panel.url) {
            if (SdkUtil.firstUI == null || SdkUtil.firstUI == undefined) {
                SdkUtil.ShowShiLin(panel);
                SdkUtil.ShowBanQuan(panel);
            }
            SdkUtil.firstUI = true;
        }

        if (panel.url.indexOf("GameRun") != -1 || panel.url.indexOf("gameMain") != -1 || panel.url.indexOf("Main") != -1 || panel.url.indexOf("Game") != -1) {
            SdkUtil.ShowYinSiBtn(panel);
            if (SdkUtil.MainUI == null || SdkUtil.MainUI == undefined) {
                SdkUtil.ShowYinSiTip(false);
            }
            SdkUtil.MainUI = true;
            if (SdkUtil.runchapingid == null) {
                // clearInterval(SdkUtil.runchapingid) ;
                // SdkUtil.runchapingid=null;
                //原生banner
                SdkUtil.runchapingid = setInterval(function () {
                    if (SdkUtil.RandomInt(0, 100) < SdkUtil.GetConfig("yscptc")) {
                        SdkUtil.ShowYuanShengMoBan();
                    }
                }, 60000);
            }
            if (SdkUtil.screenOrientation == "2") {
                // SdkUtil.CreateJiuGongHuTui(panel, {
                //     "right": 0,
                //     "centerY": 200
                // });
            } else {
                // SdkUtil.CreateJiuGongHuTui(panel, {
                //     "right": 0,
                //     "centerY": 250
                // });
            }

            // SdkUtil.ShowJiuGongHuTui()
            // SdkUtil.ShowLunBoBanner() ;
            if (SdkUtil.RandomInt(0, 100) < SdkUtil.GetConfig("yscp")) {
                SdkUtil.ShowYuanShengMoBan();
            }
            if (SdkUtil.showZhenDong == true) {
                SdkUtil.ShowZhenDongBtn(panel);
            }
            SdkUtil.CloseHuTuiBanner();
            SdkUtil.ShowPingTaiBanner();
        }

        SdkUtil.ShowVideo1();
        // if(window.morencanshu&&window.morencanshu.UpdateGamePanel)
        // {
        //     window.morencanshu.UpdateGamePanel(panel) ; 
        //     if(panel.url.indexOf("GameRun")!=-1||panel.url.indexOf("gameMain")!=-1||panel.url.indexOf("Main")!=-1||panel.url.indexOf("Game")!=-1)
        //     {
        //         if(SdkUtil.showZhenDong==true)
        //         {
        //             SdkUtil.ShowZhenDongBtn(panel) ;
        //         }
        //     }
        //     return ;
        // }
        if (panel.url.indexOf("Box") != -1 || panel.url.indexOf("ColorEgg") != -1 || panel.url.indexOf("Skin") != -1 || panel.url.indexOf("BaoXiang") != -1 || panel.url.indexOf("XuanXiang") != -1 || panel.url.indexOf("Bag") != -1) {
            if (SdkUtil.RandomInt(0, 100) < SdkUtil.GetConfig("jm")) {
                SdkUtil.ShowYuanShengMoBan();
            }
            SdkUtil.ClosePingTaiBanner();
        }
        if (panel.url.indexOf("Push") != -1 || panel.url.indexOf("Shop") != -1 || panel.url.indexOf("Sign") != -1 || panel.url.indexOf("QianDao") != -1 || panel.url.indexOf("Qiandao") != -1) {
            SdkUtil.ShowJiuGongHuTui()
            SdkUtil.CloseLunBoBanner();
            SdkUtil.CloseHuTuiBanner();
            SdkUtil.ClosePingTaiBanner();
            if (SdkUtil.RandomInt(0, 100) < SdkUtil.GetConfig("jm")) {
                SdkUtil.ShowYuanShengMoBan();
            } else {// SdkUtil.ShowYuanShengMoBan(true) ;
            }
        }
        if (panel.url.indexOf("Win") != -1 || panel.url.indexOf("shengli") != -1) {
            if (SdkUtil.RandomInt(0, 100) < SdkUtil.GetConfig("jm")) {
                SdkUtil.ShowYuanShengMoBan();
            } else {
                SdkUtil.ClosePingTaiBanner();
                SdkUtil.ShowYuanShengMoBan(true);
            }
        }
        if (panel.url.indexOf("Fail") != -1 || panel.url.indexOf("Lose") != -1 || panel.url.indexOf("Over") != -1 || panel.url.indexOf("shibai") != -1) {
            if (SdkUtil.RandomInt(0, 100) < SdkUtil.GetConfig("jm")) {
                SdkUtil.ShowYuanShengMoBan();
            }
            SdkUtil.ClosePingTaiBanner();
            SdkUtil.ShowHuTuiBanner();
        }
    },
    CloseGamePanel(url) {
        // if(window.morencanshu&&window.morencanshu.CloseGamePanel)
        // {
        //     window.morencanshu.CloseGamePanel(url) ; 
        //     return ;
        // }
        if (url) {
            if (SdkUtil.RandomInt(0, 100) >= SdkUtil.GetConfig("jm")) {
                SdkUtil.CloseYuanShengMoBan();
            }

            if (url.indexOf("Fail") != -1 || url.indexOf("Lose") != -1 || url.indexOf("Over") != -1 || url.indexOf("shibai") != -1) {
                SdkUtil.CloseHuTuiBanner();
            }
            if (url.indexOf("GameRun") != -1) {
            }
            // var kg = false ;
            // if(url.indexOf("Push")!=-1)
            // {
            //     if(SdkUtil.RandomInt(0,100)<SdkUtil.GetConfig("jmpush"))
            //     {
            //         kg = true ;
            //     }
            // }
            // if(url.indexOf("Win")!=-1)
            // {
            //     if(SdkUtil.RandomInt(0,100)<SdkUtil.GetConfig("jmwin"))
            //     {
            //         kg = true ;
            //     }
            // }
            // if(url.indexOf("Box")!=-1)
            // {
            //     if(SdkUtil.RandomInt(0,100)<SdkUtil.GetConfig("jmbox"))
            //     {
            //         kg = true ;
            //     }
            // }
            // if(kg)
            // {
            //     if(SdkUtil.adPanel&&SdkUtil.adPanel.visible==true&&SdkUtil.adPanel.getChildByName("bj")&&SdkUtil.adPanel.getChildByName("bj").event)
            //     {
            //         SdkUtil.adPanel.getChildByName("bj").event(Laya.Event.CLICK) ;
            //     }
            // }
        }
    },
    ///////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////
    GetConfig: function (v) {
        if (v == "boxBtn") {
            return 100;
        }
        if (SdkUtil.fristRun == 1) {
            if (GameConfig.config["fr"] && SdkUtil.RandomInt(0, 100) <= GameConfig.config["fr"]) {
                return 0;
            }
        }
        if (GameConfig.config[v]) {
            return GameConfig.config[v]
        }
        return 0;
    },
    //加载子包
    LoadSubpackage(callback) {
        if (SdkUtil.subpkgnum == 0) {

            if (new Date().getTime() - SdkUtil.qidongTime >= 3000) {
                if (callback != null) {
                    callback();
                }
            } else {
                let jinge = 3000 - (new Date().getTime() - SdkUtil.qidongTime);
                Laya.timer.once(jinge, this, function () {
                    if (callback != null) {
                        callback();
                    }
                })
            }
            return;
        }
        console.log("加载子包开始" + SdkUtil.subpkgnum);
        SdkUtil.LoadSubpackage2("package" + SdkUtil.subpkgnum, function () {
            SdkUtil.subpkgnum -= 1;
            SdkUtil.LoadSubpackage(callback);
        })
    },
    LoadSubpackage2(packname, callback) {
        // const loadTask = qg.loadSubpackage({
        //     name: packname,
        //     success: function (info) {
        //         if (callback != null) {
        //             callback();
        //         }
        //     },
        //     fail: function (info) {
        //         console.log("加载子包失败", info);
        //         SdkUtil.LoadSubpackage2(packname, callback);
        //     },
        //     complete: function () { }
        // })
    },
    ShowTip(v) {
        var pos = new Laya.Point(360, 700);
        if (SdkUtil.screenOrientation == "2") {
            pos = new Laya.Point(Laya.stage.width / 2, Laya.stage.height / 2);
        }
        let ui1 = Laya.stage.addChild(new GameTipUI());
        ui1.value.text = v;
        ui1.x = pos.x;
        ui1.y = pos.y;
        ui1.zOrder = 100;
        Laya.timer.frameOnce(120, this, function () {
            ui1.destroy();
        });
    },
    ShowShiLin(panel) {
        let ui1 = Laya.stage.addChild(new ShiLingTipUI());
        ui1.destroy();
        // if (SdkUtil.shilinImg == null) {
        //     SdkUtil.shilinImg = new Laya.Image("ADRes/8plus.png");
        //     panel.addChild(SdkUtil.shilinImg);
        //     SdkUtil.shilinImg.zOrder = 200;
        //     SdkUtil.shilinImg.x = 10;
        //     SdkUtil.shilinImg.y = 300;
        //     SdkUtil.shilinImg.scaleX = 0.8
        //     SdkUtil.shilinImg.scaleY = 0.8
        //     SdkUtil.shilinImg.on(Laya.Event.CLICK, this, function () {
        //         let ui1 = Laya.stage.addChild(new ShiLingTipUI());
        //         ui1.destroy();
        //         ui1.zOrder = 115;
        //         ui1.height = 720 / Laya.stage.width * Laya.stage.height;
        //         ui1.okbtn.on(Laya.Event.CLICK, this, function () {
        //             console.log("🚀 ~ file: oppoSdk.js:1230 ~ okbtn:");

        //             ui1.destroy();
        //         })
        //     })
        // }
    },
    ShowBanQuan(panel) {
        var label = new Laya.Label();
        panel.addChild(label);

        label.width = Laya.stage.width;
        label.zOrder = 100;
        label.font = "Microsoft YaHei";
        label.text = "抵制不良游戏 拒绝盗版游戏 注意自我保护 谨防受骗上当\n适度游戏益脑 沉迷游戏伤身 合理安排时间 享受健康生活\n联系邮箱：4632549858@163.com\n著作权人:" + window.GameParameter["softCompanyName"].val + "\n登记号: " + window.GameParameter["softNumber"].val + "";
        label.fontSize = 25;
        label.color = "#FFFFFF";
        label.stroke = 4;
        label.strokeColor = "#000000";
        label.align = "center";
        label.anchorX = 0.5;
        label.anchorY = 1;
        label.leading = 5;
        label.centerX = 0;
        label.y = Laya.stage.height - 70;
    },
    ShowZhenDongBtn(panel) {
        let ui1 = panel.addChild(new ZhenDongBtnUI());
        ui1.left = 130;
        ui1.zOrder = 80;
        if (SdkUtil.screenOrientation == "2") {
            ui1.top = 50;
        } else {
            ui1.top = 45;
        }
        if (window.morencanshu && window.morencanshu.shezhiV) {
            ui1.top = window.morencanshu.shezhiV;
        }
        if (SdkUtil.iszhendong) {
            ui1.btn.skin = "ADRes/zddk.png"
        } else {
            ui1.btn.skin = "ADRes/zdgb.png"
        }
        ui1.btn.on(Laya.Event.CLICK, this, function () {
            if (SdkUtil.iszhendong) {
                SdkUtil.iszhendong = false;
            } else {
                SdkUtil.iszhendong = true;
            }
            if (SdkUtil.iszhendong) {
                ui1.btn.skin = "ADRes/zddk.png"
            } else {
                ui1.btn.skin = "ADRes/zdgb.png"
            }
        })
    },
    ShowYinSiBtn(panel) {
        let ui1 = panel.addChild(new YinSiBtnUI());
        //FIX隐藏设置按钮
        ui1.visible=false;
        ui1.left = 30;
        ui1.zOrder = 80;
        if (SdkUtil.screenOrientation == "2") {
            ui1.top = 50;
        } else {
            ui1.top = 45;
        }
        if (window.morencanshu && window.morencanshu.shezhiV) {
            ui1.top = window.morencanshu.shezhiV;
        }
        ui1.btn.on(Laya.Event.CLICK, this, function () {
            SdkUtil.ShowYinSiTip(true);
        })
    },
    ShowYinSiTip(v) {
      
        // var showyinsi = Laya.LocalStorage.getItem("showyinsi");
        // if (showyinsi == "ok" && v == false) {
        //     return;
        // }
        // var pos = new Laya.Point(0, 0);
        // let ui1 = null;
        // if (SdkUtil.screenOrientation == "2") {
        //     ui1 = Laya.stage.addChild(new YinSiHUI());
        //     ui1.width = 720 / Laya.stage.height * Laya.stage.width;
        // } else {
        //     ui1 = Laya.stage.addChild(new YinSiUI());
        //     ui1.height = 720 / Laya.stage.width * Laya.stage.height;
        // }
        // ui1.x = pos.x;
        // ui1.y = pos.y;
        // ui1.zOrder = 99;

        // ui1.okbtn.visible = !v;
        // ui1.closebtn.visible = !v;
        // ui1.okbtn1.visible = v;
 
        // ui1.okbtn.on(Laya.Event.CLICK, this, function () {
        //     console.log("🚀 ~ file: oppoSdk.js:1328 ~ okbtn:");

        //     Laya.LocalStorage.setItem("showyinsi", "ok");
        //     ui1.destroy();
        // })
        // ui1.closebtn.on(Laya.Event.CLICK, this, function () {
        //     // SdkUtil.ShowTip("同意才能进入游戏");
        //     // qg.exitApplication({})
        // })
        // ui1.okbtn1.on(Laya.Event.CLICK, this, function () {
        //     console.log("🚀 ~ file: oppoSdk.js:1338 ~ okbtn1:");

        //     ui1.destroy();
        // })

        // ui1.text2.text = ui1.text2.text.replace(/nn/g, "\n")
        // ui1.prevY = 0;
        // ui1.text2.scrollY = 0
        // ui1.panel1.on(Laya.Event.MOUSE_DOWN, this, function (e) {
        //     ui1.prevY = ui1.panel1.mouseY;
        // });
        // ui1.panel1.on(Laya.Event.MOUSE_MOVE, this, function (e) {

        //     let nowY = ui1.panel1.mouseY;
        //     ui1.text2.scrollY += ui1.prevY - nowY;
        //     ui1.prevY = nowY;
        // });

    },
    //数据上报 
    ReportMonitor(id) {
        // if (qg.reportMonitor) {
        //     qg.reportMonitor('game_scene', 0);
        // }
        SdkUtil.TDGuanQia(2, "-1");
    },
    ShowIconLunBoUI(panel) {
        panel.visible = false;
    },
    ShowAddIcon() {
        if (new Date().getTime() < SdkUtil.addIconShowTime) {
            return;
        }
        SdkUtil.addIconShowTime = new Date().getTime() + 120000;
        // qg.hasShortcutInstalled({
        //     success: function (status) {
        //         if (status) {
        //             console.log('创建成功')
        //             SdkUtil.TDEvent("创建ICON成功")
        //         } else {
        //             console.log('未创建')
        //             qg.installShortcut({
        //                 message: "添加之后可快速启动游戏哦",
        //                 success: function () {
        //                 }
        //             })
        //         }
        //     }
        // })

    },
    //是否显示分享按钮
    IsShowShareBtn() {
        return false;
    },
    luzhiKaishi() {
        // SdkUtil.CloseHuTuiBanner() ;
        SdkUtil.ShowJiuGongHuTui()
        SdkUtil.CloseLunBoBanner();
    },
    luzhijieshu() { },
    fenxiangVideo(endCB) { },
    //集成到界面中的广告
    ShowNeiZhiAD(panel, id) {
        panel.visible = false;
        // if(new Date().getTime()<SdkUtil.bnanerShowTime)
        // {
        //     panel.visible = false ;
        //     return ;
        // }
        // var isShow = true ;
        // SdkUtil.adPanel = panel ;
        // SdkUtil.adPanel.visible = false ;
        // SdkUtil.neizhiADID = id ;
        // SdkUtil.createNativeAd02();
        return false;
    },
    ShowBanner(adid) { },
    CloseBanner() { },
    ShowPingTaiBanner() {
        // if (SdkUtil.bannerId == "") {
        //     return;
        // }
        // if (SdkUtil.bannerAd) {
        //     SdkUtil.bannerAd.show();
        //     return;
        // }
        // SdkUtil.bannerAd = window['qg'].createBannerAd({
        //     adUnitId: SdkUtil.bannerId,
        // });
        // SdkUtil.bannerAd.show();
    },
    ClosePingTaiBanner() {
        if (SdkUtil.bannerAd) {
            SdkUtil.bannerAd.hide();
        }
    },
    ShowLunBoBanner() {
        // if (SdkUtil.HTLunBoBannerId == "") {
        //     return;
        // }
        // if (qg.getSystemInfoSync().platformVersionCode >= 1090) {
        //     if (SdkUtil.LunBoBannerAd) {
        //         SdkUtil.LunBoBannerAd.show().then(function () {
        //             SdkUtil.CloseJiuGongHuTui();
        //         }).catch(function (error) {
        //             console.log('show fail with:' + error.errCode + ',' + error.errMsg)
        //         })
        //         return;
        //     }
        //     SdkUtil.LunBoBannerAd = qg.createGameBannerAd({
        //         adUnitId: SdkUtil.HTLunBoBannerId,
        //         style: {
        //             top: qg.getSystemInfoSync().screenHeight - 300,
        //             left: 30,
        //             orientation: 'horizontal'
        //         }
        //     })
        //     SdkUtil.LunBoBannerAd.show().then(function () {
        //         SdkUtil.CloseJiuGongHuTui();
        //     }).catch(function (error) {
        //         console.log('show fail with:' + error.errCode + ',' + error.errMsg)
        //     })
        // } else {
        // }
    },
    CloseLunBoBanner() {
        if (SdkUtil.LunBoBannerAd) {
            SdkUtil.LunBoBannerAd.hide();
        }
    },
    ShowHuTuiBanner() {
        // if (SdkUtil.bannerHTID == "") {
        //     return;
        // }
        // if (qg.getSystemInfoSync().platformVersionCode >= 1076) {
        //     if (SdkUtil.gameBannerAd) {
        //         SdkUtil.gameBannerAd.show().then(function () {
        //             console.log('show success')
        //         }).catch(function (error) {
        //             console.log('show fail with:' + error.errCode + ',' + error.errMsg)
        //         })
        //         return;
        //     }
        //     SdkUtil.gameBannerAd = qg.createGameBannerAd({
        //         adUnitId: SdkUtil.bannerHTID
        //     })
        //     SdkUtil.gameBannerAd.show().then(function () {
        //         console.log('show success')
        //     }).catch(function (error) {
        //         console.log('show fail with:' + error.errCode + ',' + error.errMsg)
        //     })
        // } else {
        // }
    },
    CloseHuTuiBanner() {
        if (SdkUtil.gameBannerAd) {
            SdkUtil.gameBannerAd.hide();
        }
    },
    ShowVideo1() {
        var kaipin1 = SdkUtil.GetConfig("skp");
        if (kaipin1 == 0 || kaipin1 == null) {
            return false;
        }

        var ss = kaipin1.split("_");
        if (ss[0] == null || ss[1] == null || ss[2] == null) {
            return false;
        }
        if (SdkUtil.RandomInt(0, 100) >= parseInt(ss[0])) {
            return false;
        }
        if (SdkUtil.preClickTime1 == null) {
            SdkUtil.preClickTime1 = SdkUtil.qidongTime + parseInt(ss[1]);
        }

        if (new Date().getTime() < SdkUtil.preClickTime1) {
            return false;
        }
        SdkUtil.preClickTime1 = new Date().getTime() + parseInt(ss[2]);
        SdkUtil.TDEvent("视频点击2");
        window["SdkUtil"].ShowVideo(function (code) {
            if (code == 1) {
                SdkUtil.TDEvent("视频完成2");
            }
        });

        return true;
    },
    ShowVideo(callback) {
        callback(1);
        // if (new Date().getTime() - SdkUtil.preClickTime <= 2000) {
        //     if (callback != null) {
        //         callback(0);
        //         callback = null;
        //     }
        //     SdkUtil.ShowTip("正在加载视频请稍等")
        //     return;
        // }
        // SdkUtil.preClickTime = new Date().getTime();

        // var videoAd = qg.createRewardedVideoAd({
        //     posId: SdkUtil.videoId
        // })
        // videoAd.onClose((res) => {
        //     if (res.isEnded) {
        //         console.log('激励视频广告完成，发放奖励')
        //         if (callback != null) {
        //             callback(1);
        //             callback = null;
        //         }
        //     } else {
        //         console.log('激励视频广告取消关闭，不发放奖励')
        //         if (callback != null) {
        // callback(0);
        //             callback = null;
        //         }
        //     }
        // }
        // );
        // videoAd.onError(function (err) {
        //     if (err) {
        //         if (callback != null) {
        //             callback(0);
        //             callback = null;
        //         }
        //         console.log("激励视频加载错误:" + JSON.stringify(err));
        //         SdkUtil.ShowTip("正在加载视频请稍等")
        //     }
        // })
        // videoAd.onLoad(function () {
        //     console.log("激励视频加载成功");
        //     videoAd.show();
        // })
        // videoAd.load();
    },
    //插屏
    ShowChaPing(callback) { },
    ShowYuanShengMoBan(isBotton) {
        // if (SdkUtil.yuanshengmoban == "") {
        //     return;
        // }
        // if (qg.createCustomAd) {
        //     SdkUtil.CloseYuanShengMoBan();
        //     let sd = qg.getSystemInfoSync()
        //     let yy = sd.screenHeight * 0.5;
        //     if (isBotton) {
        //         yy = sd.screenHeight - 550;
        //     }
        //     SdkUtil.yuanshengmobanAd = qg.createCustomAd({
        //         adUnitId: SdkUtil.yuanshengmoban,
        //         style: {
        //             top: yy,
        //             left: 210,
        //             width: 700
        //         }
        //     })
        //     SdkUtil.yuanshengmobanAd.show().then(() => {
        //         console.log('show success')
        //     }
        //     ).catch((error) => {
        //         console.log('show fail with:' + error.errCode + ',' + error.errMsg)
        //     }
        //     )
        // }
    },
    CloseYuanShengMoBan() {
        if (SdkUtil.yuanshengmobanAd && SdkUtil.yuanshengmobanAd.destroy) {
            SdkUtil.yuanshengmobanAd.destroy();
            SdkUtil.yuanshengmobanAd = null;
        }
    },
    CreateJiuGongHuTui(panel, data) {
        // if (SdkUtil.jiugongHTId == "") {
        //     return;
        // }
        // if (qg.getSystemInfoSync().platformVersionCode >= 1076) {
        //     var iconUI = panel.addChildAt(new HTMoreGameUI(), 2);
        //     iconUI.left = data.left;
        //     iconUI.right = data.right;
        //     iconUI.top = data.top;
        //     iconUI.bottom = data.bottom;
        //     iconUI.centerX = data.centerX;
        //     iconUI.centerY = data.centerY;
        //     iconUI.zOrder = 9999;
        //     SdkUtil.MoreGameUI = iconUI;

        //     iconUI.ClickBtn = function () {
        //         SdkUtil.TDEvent("互推九宫点击");
        //         var gamePortalAd = qg.createGamePortalAd({
        //             adUnitId: SdkUtil.jiugongHTId
        //         })
        //         gamePortalAd.load().then(function () {
        //             console.log('load success')
        //             gamePortalAd.show().then(function () {
        //                 console.log('show success')
        //                 SdkUtil.TDEvent("互推九宫展示");
        //             }).catch(function (error) {
        //                 console.log('show fail with:' + error.errCode + ',' + error.errMsg)
        //                 SdkUtil.ShowTip("暂无内容请稍后再试");
        //             })
        //         }).catch(function (error) {
        //             console.log('load fail with:' + error.errCode + ',' + error.errMsg)
        //             SdkUtil.ShowTip("暂无内容请稍后再试");
        //         })

        //     }
        //     iconUI.DownBtn = function () {
        //         if (window.UiManager) {
        //             window.UiManager.uiClick = true;
        //         }
        //     }
        //     iconUI.on(Laya.Event.CLICK, iconUI, iconUI.ClickBtn);
        //     iconUI.on(Laya.Event.MOUSE_DOWN, iconUI, iconUI.DownBtn);
        // }
    },
    ShowJiuGongHuTui() {
        if (SdkUtil.MoreGameUI) {
            SdkUtil.MoreGameUI.visible = true;
        }
    },
    CloseJiuGongHuTui() {
        if (SdkUtil.MoreGameUI) {
            SdkUtil.MoreGameUI.visible = false;
        }
    },
    // ShowInserNativeAd(createNative01)
    // {
    //     SdkUtil.adPanel.visible = true ;
    //     SdkUtil.adPanel.getChildByName("close").offAll(Laya.Event.CLICK) ;
    //     SdkUtil.adPanel.getChildByName("bj").offAll(Laya.Event.CLICK) ;
    //     SdkUtil.adPanel.getChildByName("click").offAll(Laya.Event.CLICK) ;

    //     SdkUtil.nativeInsertUI = SdkUtil.adPanel ;

    //     var adinfo = SdkUtil.nativeAdList02[0] ;
    //     var nativeAd = SdkUtil.nativeAd02 ;
    //     if(adinfo.imgUrlList.length>0)
    //     {
    //         if(SdkUtil.neizhiADID==10)
    //         {
    //             SdkUtil.adPanel.getChildByName("icon").skin = adinfo.imgUrlList[SdkUtil.RandomInt(0,adinfo.imgUrlList.length-1)] ;
    //         }
    //         else
    //         {
    //             SdkUtil.adPanel.getChildByName("bj").skin = adinfo.imgUrlList[SdkUtil.RandomInt(0,adinfo.imgUrlList.length-1)] ;
    //             SdkUtil.adPanel.getChildByName("icon").visible = false ;
    //         }

    //     }
    //     if(adinfo.iconUrlList.length>0)
    //     {
    //         SdkUtil.adPanel.getChildByName("icon").skin = adinfo.iconUrlList[SdkUtil.RandomInt(0,adinfo.iconUrlList.length-1)] ;
    //     }
    //     SdkUtil.adPanel.getChildByName("title").text = adinfo.title ;
    //     SdkUtil.adPanel.getChildByName("des").text = adinfo.desc ;
    //     SdkUtil.adPanel.getChildByName("close").on(Laya.Event.CLICK,this,function()
    //     {
    //         SdkUtil.adPanel.visible = false ;
    //         nativeAd.destroy() ;
    //         SdkUtil.nativeAdList02 = null ;
    //         if(createNative01)
    //         {
    //             SdkUtil.IconNativeUI.destroy();
    //             SdkUtil.IconNativeUI = null ;
    //             SdkUtil.createNativeAd01();
    //         }
    //         SdkUtil.nativeInsertUI = null ;

    //     });
    //     SdkUtil.adPanel.getChildByName("bj").on(Laya.Event.CLICK,this,function()
    //     {
    //         console.log("点击广告。。。")
    //         SdkUtil.adPanel.visible = false ;
    //         nativeAd.reportAdClick({
    //             adId: adinfo.adId 
    //         })
    //         nativeAd.destroy() ;
    //         SdkUtil.nativeAdList02 = null ;

    //         if(createNative01)
    //         {
    //             SdkUtil.IconNativeUI.destroy();
    //             SdkUtil.IconNativeUI = null ;
    //             SdkUtil.createNativeAd01();
    //         }
    //         SdkUtil.nativeInsertUI = null ;
    //         SdkUtil.TDEvent("oppo原生点击"+ SdkUtil.nativeADTag[SdkUtil.neizhiADID],{"type":"bj"}) ;
    //     })
    //     SdkUtil.adPanel.getChildByName("click").on(Laya.Event.CLICK,this,function()
    //     {
    //         console.log("点击广告。。。")
    //         SdkUtil.adPanel.visible = false ;
    //         nativeAd.reportAdClick({
    //             adId: adinfo.adId 
    //         })
    //         nativeAd.destroy() ;
    //         SdkUtil.nativeAdList02 = null ;

    //         if(createNative01)
    //         {
    //             SdkUtil.IconNativeUI.destroy();
    //             SdkUtil.IconNativeUI = null ;
    //             SdkUtil.createNativeAd01();
    //         }
    //         SdkUtil.nativeInsertUI = null ;
    //         SdkUtil.TDEvent("oppo原生点击"+ SdkUtil.nativeADTag[SdkUtil.neizhiADID],{"type":"button"}) ;
    //     })

    //     nativeAd.reportAdShow({
    //         adId: adinfo.adId 
    //     })
    //     SdkUtil.CloseBanner() ;
    //     SdkUtil.TDEvent("oppo原生展示"+ SdkUtil.nativeADTag[SdkUtil.neizhiADID]) ;
    // },
    // ShowIconNativeAd()
    // {
    //     if(SdkUtil.IconNativeUI!=null)
    //     {
    //         return ;
    //     }
    //     var ui1 = null ;
    //     ui1 = Laya.stage.addChild(new NativeIconUI());
    //     ui1.x = -500 ;
    //     ui1.y = -500 ;
    //     ui1.zOrder = 100 ;
    //     SdkUtil.IconNativeUI = ui1 ;

    //     var adinfo = SdkUtil.nativeAdList01[0] ;
    //     var nativeAd = SdkUtil.nativeAd01 ;
    //     if(adinfo.iconUrlList.length>0)
    //     {
    //         ui1.icon.skin = adinfo.iconUrlList[SdkUtil.RandomInt(0,adinfo.iconUrlList.length-1)] ;
    //     }
    //     else
    //     {
    //         ui1.icon.skin = adinfo.imgUrlList[SdkUtil.RandomInt(0,adinfo.imgUrlList.length-1)] ;
    //     }
    //     ui1.title.text = adinfo.title ;

    //     ui1.bj.on(Laya.Event.CLICK,this,function()
    //     {
    //         console.log("点击广告。。。")
    //         ui1.destroy() ;
    //         nativeAd.reportAdClick({
    //             adId: adinfo.adId 
    //         })
    //         SdkUtil.IconNativeUI = null ;
    //         nativeAd.destroy() ;
    //         SdkUtil.nativeAdList01 = null ;

    //         SdkUtil.createNativeAd01();

    //     })
    //     nativeAd.reportAdShow({
    //         adId: adinfo.adId 
    //     })
    // },

    // ShowChaPingNativeAd()
    // {
    //     var ui1 = null ;
    //     ui1 = Laya.stage.addChild(new NativeInsertUI());
    //     if(SdkUtil.screenOrientation=="2")
    //     {
    //         ui1.height =  Laya.stage.height ;
    //         ui1.width =  Laya.stage.width ;
    //     }
    //     else
    //     {
    //         ui1.height = 720 / Laya.stage.width  * Laya.stage.height ;
    //     }
    //     ui1.x = 0 ;
    //     ui1.y = 0 ;
    //     ui1.zOrder = 9999 ;

    //     var adinfo = SdkUtil.nativeAdList03[0] ;
    //     var nativeAd = SdkUtil.nativeChaPingAd ;
    //     if(adinfo.imgUrlList.length>0)
    //     {
    //         ui1.bj.skin = adinfo.imgUrlList[SdkUtil.RandomInt(0,adinfo.imgUrlList.length-1)] ;
    //         ui1.icon.visible = false ;
    //     }
    //     if(adinfo.iconUrlList.length>0)
    //     {
    //         ui1.icon.skin = adinfo.iconUrlList[SdkUtil.RandomInt(0,adinfo.iconUrlList.length-1)] ;
    //     }

    //     ui1.title.text = adinfo.title ;
    //     ui1.des.text = adinfo.desc ;
    //     ui1.close.on(Laya.Event.CLICK,this,function()
    //     {
    //         ui1.destroy() ;
    //         nativeAd.destroy() ;
    //         SdkUtil.nativeAdList03 = null ;
    //     });
    //     ui1.click.on(Laya.Event.CLICK,this,function()
    //     {
    //         console.log("点击广告。。。")
    //         ui1.destroy() ;
    //         nativeAd.reportAdClick({
    //             adId: adinfo.adId 
    //         })
    //         nativeAd.destroy() ;
    //         SdkUtil.nativeAdList03 = null ;
    //         SdkUtil.TDEvent("oppo原生点击插屏",{"type":"click"}) ;
    //     })
    //     ui1.bj.on(Laya.Event.CLICK,this,function()
    //     {
    //         console.log("点击广告。。。")
    //         ui1.destroy() ;
    //         nativeAd.reportAdClick({
    //             adId: adinfo.adId 
    //         })
    //         nativeAd.destroy() ;
    //         SdkUtil.nativeAdList03 = null ;
    //         SdkUtil.TDEvent("oppo原生点击插屏",{"type":"bj"}) ;
    //     })
    //     nativeAd.reportAdShow({
    //         adId: adinfo.adId 
    //     })
    //     SdkUtil.TDEvent("oppo原生展示插屏") ;
    // },
    //原生广告
    // nativeInsertUI:null,   //原生UI
    // nativeDatas:[],
    // nativeDataIndex:0,
    // isLoadNativeDatas:false,
    // nativeAd01:null ,
    // nativeAd02:null ,
    // nativeChaPingAd:null ,
    // nativeAdList01:null,
    // nativeAdList02:null,
    // nativeAdList03:null,

    // createNativeAd01()
    // {
    // if(SdkUtil.nativeAd01)
    // {
    //     SdkUtil.nativeAd01.destroy() ;
    // }
    // SdkUtil.nativeAd01 = qg.createNativeAd({ 
    //     posId: 193248
    // })
    // SdkUtil.nativeAd01.onLoad(function(res) {
    //     console.log("原生广告加载" ,JSON.stringify(res.adList));
    //     SdkUtil.nativeAdList01 = res.adList;
    //     SdkUtil.ShowIconNativeAd() ;
    // })
    // SdkUtil.nativeAd01.onError(function(res) {
    //     console.log("原生广告加载错误" ,JSON.stringify(res) );
    //     // nativeAd.destroy();
    //     Laya.timer.once(10000,this,function()
    //     {
    //         SdkUtil.nativeAd01.load();
    //     })
    // })
    // SdkUtil.nativeAd01.load();
    // },
    // createNativeAd02()
    // {
    //     SdkUtil.nativeAd02 = qg.createNativeAd({ 
    //         posId: SdkUtil.nativeAD[SdkUtil.neizhiADID]
    //     })
    //     SdkUtil.nativeAd02.onLoad(function(res) {
    //         console.log("原生广告加载" ,JSON.stringify(res.adList));
    //         SdkUtil.nativeAdList02 = res.adList;
    //         SdkUtil.ShowInserNativeAd() ;
    //     })
    //     SdkUtil.nativeAd02.onError(function(res) {
    //         console.log("原生广告加载错误" ,JSON.stringify(res) );
    //         SdkUtil.nativeAd02.destroy();
    //         if(SdkUtil.nativeAdList01)
    //         {
    //             SdkUtil.nativeAd02 = SdkUtil.nativeAd01 ;
    //             SdkUtil.nativeAdList02 = SdkUtil.nativeAdList01 ;
    //             SdkUtil.ShowInserNativeAd(true) ;
    //             SdkUtil.nativeAdList01 = null ;
    //         }
    //         else
    //         {
    //             // SdkUtil.ShowInserPingTai() ;
    //         }
    //     })
    //     SdkUtil.nativeAd02.load();
    // },

    // createChaPingNativeAd(id)
    // {
    //     if(new Date().getTime() - SdkUtil.showchapingTime<=10000)
    //     {
    //         return ;
    //     }
    //     SdkUtil.showchapingTime = new Date().getTime() ;

    //     if(SdkUtil.nativeAD[id]==""||SdkUtil.nativeAD[id]==undefined)
    //     {
    //         return ;
    //     }
    //     if(SdkUtil.nativeChaPingAd)
    //     {
    //         SdkUtil.nativeChaPingAd = null ;
    //     }
    //     SdkUtil.nativeChaPingAd = qg.createNativeAd({ 
    //         posId: SdkUtil.nativeAD[id]
    //     })
    //     SdkUtil.nativeChaPingAd.onLoad(function(res) {
    //         console.log("原生广告加载" ,JSON.stringify(res.adList));
    //         SdkUtil.nativeAdList03 = res.adList;
    //         SdkUtil.ShowChaPingNativeAd() ;
    //     })
    //     SdkUtil.nativeChaPingAd.onError(function(res) {
    //         console.log("原生广告加载错误" ,JSON.stringify(res) );
    //     })
    //     SdkUtil.nativeChaPingAd.load();
    // },

    TDInit() {
        if (window["TDAPP"] != null) {
            console.log("统计....：");
        }
    },
    TDGuanQia(state, missionId) {
        if (window["TDAPP"] != null) {
            if (state == 1) {
                SdkUtil.curMissionId = "" + missionId;
                TDAPP.onEvent("关卡统计", null, {
                    "开始": "" + missionId
                });
            }
            if (state == 2) {
                TDAPP.onEvent("关卡统计", null, {
                    "胜利": "" + missionId
                });
            }
            if (state == 3) {
                TDAPP.onEvent("关卡统计", null, {
                    "失败": "" + missionId
                });
            }
        }
    },
    TDEvent(eventId, eventData) {
        if (window["TDAPP"] != null) {
            if (SdkUtil.curMissionId == null) {
                SdkUtil.curMissionId = "0";
            }
            if (eventData == null) {
                eventData = {};
            }
            eventData["level"] = SdkUtil.curMissionId;
            // console.log("统计事件名称："+eventId) ;
            TDAPP.onEvent(eventId, null, eventData);
        }
    },

    //////////////////////
    RandomInt(min, max) {
        return Math.round(Math.random() * (max - min) + min);
    },

};
